import * as GLOBAL from './GlobalConstants';

export const URL_FETCH_INGRESSOS_VENDIDOS = GLOBAL.LARAVEL_BASE_URL + "tickets/user/json";
export const FETCH_INGRESSOS_VENDIDOS = "FETCH_INGRESSOS_VENDIDOS";
export const RECEIVE_INGRESSOS_VENDIDOS = "RECEIVE_INGRESSOS_VENDIDOS";
